"""
Fast Backtest Engine for {strategy_name}
Generated by CBT Framework (Fast Engine: Numba JIT)

Numba-compiled backtest loop for maximum performance.
No pandas in the hot path - pure NumPy arrays + Numba @njit.
"""

import numpy as np
from numba import njit
from typing import Dict
from dataclasses import dataclass
import yaml
import csv
from datetime import datetime


@njit
def run_backtest_loop(
    open_prices: np.ndarray,
    high_prices: np.ndarray,
    low_prices: np.ndarray,
    close_prices: np.ndarray,
    directions: np.ndarray,
    confidences: np.ndarray,
    initial_capital: float,
    percent_per_trade: float,
    leverage: float,
    stop_loss_pct: float,
    take_profit_pct: float,
    maker_fee: float,
    taker_fee: float,
    slippage: float,
    max_positions: int,
) -> tuple:
    """
    Numba-compiled backtest loop.

    Returns:
        equity_curve: float64 array of equity at each bar
        trade_pnls: float64 array of trade PnL values
        trade_entries: int64 array of entry bar indices
        trade_exits: int64 array of exit bar indices
        trade_directions: int64 array of trade directions (1/-1)
        trade_entry_prices: float64 array of entry prices
        trade_exit_prices: float64 array of exit prices
        num_trades: int64 number of trades executed
    """
    n = len(close_prices)

    # Pre-allocate output arrays (max possible trades)
    max_trades = n // 2
    trade_pnls = np.empty(max_trades, dtype=np.float64)
    trade_entries = np.empty(max_trades, dtype=np.int64)
    trade_exits = np.empty(max_trades, dtype=np.int64)
    trade_directions = np.empty(max_trades, dtype=np.int64)
    trade_entry_prices = np.empty(max_trades, dtype=np.float64)
    trade_exit_prices = np.empty(max_trades, dtype=np.float64)

    equity_curve = np.empty(n, dtype=np.float64)
    equity = initial_capital
    num_trades = 0

    # Position state
    in_position = False
    position_direction = 0
    position_size = 0.0
    entry_price = 0.0
    stop_loss = 0.0
    take_profit = 0.0
    entry_bar = 0

    for i in range(n):
        current_price = close_prices[i]

        # Check exits first
        if in_position:
            exit_triggered = False
            exit_price = current_price

            # Check stop loss
            if stop_loss > 0:
                if position_direction == 1 and low_prices[i] <= stop_loss:
                    exit_price = stop_loss
                    exit_triggered = True
                elif position_direction == -1 and high_prices[i] >= stop_loss:
                    exit_price = stop_loss
                    exit_triggered = True

            # Check take profit
            if not exit_triggered and take_profit > 0:
                if position_direction == 1 and high_prices[i] >= take_profit:
                    exit_price = take_profit
                    exit_triggered = True
                elif position_direction == -1 and low_prices[i] <= take_profit:
                    exit_price = take_profit
                    exit_triggered = True

            # Check signal reversal
            if not exit_triggered and directions[i] != 0 and directions[i] != position_direction:
                exit_triggered = True
                exit_price = current_price

            if exit_triggered:
                # Apply slippage
                if position_direction == 1:
                    exit_price *= (1 - slippage / 100)
                else:
                    exit_price *= (1 + slippage / 100)

                # Calculate PnL
                if position_direction == 1:
                    pnl = position_size * (exit_price - entry_price)
                else:
                    pnl = position_size * (entry_price - exit_price)

                # Subtract exit fee
                fee = position_size * exit_price * (taker_fee / 100)
                pnl -= fee

                equity += pnl
                in_position = False

                # Record trade
                trade_pnls[num_trades] = pnl
                trade_entries[num_trades] = entry_bar
                trade_exits[num_trades] = i
                trade_directions[num_trades] = position_direction
                trade_entry_prices[num_trades] = entry_price
                trade_exit_prices[num_trades] = exit_price
                num_trades += 1

        # Check entries
        if not in_position and directions[i] != 0 and confidences[i] > 0:
            position_direction = int(directions[i])
            risk_amount = equity * (percent_per_trade / 100) * leverage

            # Apply slippage to entry
            if position_direction == 1:
                entry_price = current_price * (1 + slippage / 100)
            else:
                entry_price = current_price * (1 - slippage / 100)

            position_size = risk_amount / entry_price

            # Subtract entry fee
            fee = position_size * entry_price * (taker_fee / 100)
            equity -= fee

            # Set stop loss and take profit
            if stop_loss_pct > 0:
                if position_direction == 1:
                    stop_loss = entry_price * (1 - stop_loss_pct / 100)
                else:
                    stop_loss = entry_price * (1 + stop_loss_pct / 100)
            else:
                stop_loss = 0.0

            if take_profit_pct > 0:
                if position_direction == 1:
                    take_profit = entry_price * (1 + take_profit_pct / 100)
                else:
                    take_profit = entry_price * (1 - take_profit_pct / 100)
            else:
                take_profit = 0.0

            entry_bar = i
            in_position = True

        equity_curve[i] = equity

    return (
        equity_curve,
        trade_pnls[:num_trades],
        trade_entries[:num_trades],
        trade_exits[:num_trades],
        trade_directions[:num_trades],
        trade_entry_prices[:num_trades],
        trade_exit_prices[:num_trades],
        num_trades,
    )


@dataclass
class BacktestResults:
    """Container for backtest results and metrics."""
    total_return: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    max_drawdown_duration: int
    win_rate: float
    profit_factor: float
    total_trades: int
    avg_trade_pnl: float
    best_trade: float
    worst_trade: float
    avg_win: float
    avg_loss: float
    expectancy: float
    calmar_ratio: float
    equity_curve: np.ndarray
    trade_pnls: np.ndarray
    trade_entries: np.ndarray
    trade_exits: np.ndarray
    trade_directions: np.ndarray


class FastBacktestEngine:
    """Orchestrates the Numba-compiled backtest loop."""

    def __init__(self, config_path: str = "config.yaml"):
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)

    def run(self, backtest_arrays: Dict[str, np.ndarray]) -> BacktestResults:
        """
        Run backtest using Numba JIT-compiled loop.

        Args:
            backtest_arrays: Dict from FastStrategy.get_backtest_arrays()

        Returns:
            BacktestResults with all metrics
        """
        config = self.config

        # Extract parameters
        initial_capital = config['account']['initial_capital']
        percent_per_trade = config['sizing']['percent_per_trade']
        leverage = config['leverage']['default'] if config['leverage']['enabled'] else 1.0
        stop_loss_pct = config['risk']['stop_loss']['percent'] if config['risk']['stop_loss']['enabled'] else 0.0
        take_profit_pct = config['risk']['take_profit']['percent'] if config['risk']['take_profit']['enabled'] else 0.0
        maker_fee = config['fees']['maker']
        taker_fee = config['fees']['taker']
        slippage = config['fees']['slippage']
        max_positions = config['sizing']['max_positions']

        # Run Numba-compiled loop
        results = run_backtest_loop(
            open_prices=backtest_arrays['open'],
            high_prices=backtest_arrays['high'],
            low_prices=backtest_arrays['low'],
            close_prices=backtest_arrays['close'],
            directions=backtest_arrays['directions'],
            confidences=backtest_arrays['confidences'],
            initial_capital=initial_capital,
            percent_per_trade=percent_per_trade,
            leverage=leverage,
            stop_loss_pct=stop_loss_pct,
            take_profit_pct=take_profit_pct,
            maker_fee=maker_fee,
            taker_fee=taker_fee,
            slippage=slippage,
            max_positions=max_positions,
        )

        (equity_curve, trade_pnls, trade_entries, trade_exits,
         trade_directions, trade_entry_prices, trade_exit_prices,
         num_trades) = results

        # Calculate metrics
        metrics = self._calculate_metrics(
            equity_curve, trade_pnls, initial_capital
        )

        return BacktestResults(
            equity_curve=equity_curve,
            trade_pnls=trade_pnls,
            trade_entries=trade_entries,
            trade_exits=trade_exits,
            trade_directions=trade_directions,
            **metrics,
        )

    def _calculate_metrics(
        self,
        equity_curve: np.ndarray,
        trade_pnls: np.ndarray,
        initial_capital: float,
    ) -> dict:
        """Calculate performance metrics from results."""
        final_equity = equity_curve[-1]
        total_return = (final_equity - initial_capital) / initial_capital * 100

        # Returns for Sharpe/Sortino
        returns = np.diff(equity_curve) / equity_curve[:-1]
        returns = returns[~np.isnan(returns)]

        # Sharpe Ratio (annualized, assuming daily)
        if len(returns) > 0 and np.std(returns) > 0:
            sharpe = np.mean(returns) / np.std(returns) * np.sqrt(252)
        else:
            sharpe = 0.0

        # Sortino Ratio
        downside = returns[returns < 0]
        if len(downside) > 0:
            sortino = np.mean(returns) / np.std(downside) * np.sqrt(252)
        else:
            sortino = sharpe

        # Max Drawdown
        peak = np.maximum.accumulate(equity_curve)
        drawdown = (equity_curve - peak) / peak
        max_dd = np.min(drawdown) * 100

        # Max Drawdown Duration
        dd_duration = 0
        max_dd_duration = 0
        for i in range(len(equity_curve)):
            if equity_curve[i] < peak[i]:
                dd_duration += 1
                max_dd_duration = max(max_dd_duration, dd_duration)
            else:
                dd_duration = 0

        # Trade metrics
        num_trades = len(trade_pnls)
        if num_trades > 0:
            wins = trade_pnls[trade_pnls > 0]
            losses = trade_pnls[trade_pnls <= 0]
            win_rate = len(wins) / num_trades * 100
            avg_trade = np.mean(trade_pnls)
            best_trade = np.max(trade_pnls)
            worst_trade = np.min(trade_pnls)
            avg_win = np.mean(wins) if len(wins) > 0 else 0
            avg_loss = np.mean(losses) if len(losses) > 0 else 0
            profit_factor = abs(np.sum(wins) / np.sum(losses)) if np.sum(losses) != 0 else float('inf')
            expectancy = avg_trade
        else:
            win_rate = avg_trade = best_trade = worst_trade = 0
            avg_win = avg_loss = profit_factor = expectancy = 0

        # Calmar
        calmar = total_return / abs(max_dd) if max_dd != 0 else 0

        return {
            'total_return': total_return,
            'sharpe_ratio': sharpe,
            'sortino_ratio': sortino,
            'max_drawdown': max_dd,
            'max_drawdown_duration': max_dd_duration,
            'win_rate': win_rate,
            'profit_factor': profit_factor,
            'total_trades': num_trades,
            'avg_trade_pnl': avg_trade,
            'best_trade': best_trade,
            'worst_trade': worst_trade,
            'avg_win': avg_win,
            'avg_loss': avg_loss,
            'expectancy': expectancy,
            'calmar_ratio': calmar,
        }

    def save_results(self, results: BacktestResults, exp_id: str) -> None:
        """Save results to YAML and trade log to CSV."""
        # Save metrics to YAML
        metrics = {
            'experiment_id': exp_id,
            'timestamp': datetime.now().isoformat(),
            'performance': {
                'total_return': round(results.total_return, 2),
                'sharpe_ratio': round(results.sharpe_ratio, 4),
                'sortino_ratio': round(results.sortino_ratio, 4),
                'max_drawdown': round(results.max_drawdown, 2),
                'max_drawdown_duration': int(results.max_drawdown_duration),
                'calmar_ratio': round(results.calmar_ratio, 4),
            },
            'trades': {
                'total': int(results.total_trades),
                'win_rate': round(results.win_rate, 2),
                'profit_factor': round(results.profit_factor, 4),
                'avg_pnl': round(results.avg_trade_pnl, 2),
                'best': round(results.best_trade, 2),
                'worst': round(results.worst_trade, 2),
                'avg_win': round(results.avg_win, 2),
                'avg_loss': round(results.avg_loss, 2),
                'expectancy': round(results.expectancy, 2),
            },
            'engine': 'fast (Polars + NumPy + Numba)',
        }

        with open(f'experiments/{exp_id}.yaml', 'w') as f:
            yaml.dump(metrics, f, default_flow_style=False)

        # Save equity curve
        np.save(f'experiments/{exp_id}_equity.npy', results.equity_curve)

        # Save trade log to CSV
        with open(f'trades/{exp_id}_trades.csv', 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['entry_bar', 'exit_bar', 'direction', 'pnl'])
            for i in range(results.total_trades):
                writer.writerow([
                    results.trade_entries[i],
                    results.trade_exits[i],
                    results.trade_directions[i],
                    round(results.trade_pnls[i], 4),
                ])

        print(f"Results saved to experiments/{exp_id}.yaml")
        print(f"Trade log saved to trades/{exp_id}_trades.csv")
